export const ADD_TO_BUSKET = "ADD_TO_BUSKET";
export const DELETE_FROM_BUSKET = "DELETE_FROM_BUSKET";
export const GET_BUSKET_TOTAL_PRICE = "GET_BUSKET_TOTAL_PRICE";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCTS_PAGE = "GET_PRODUCTS_PAGE";